2020-01-13 11:18:57,229 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:19:21,278 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:19:52,565 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:30:01,861 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:33:55,674 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:57:23,173 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:58:00,598 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:58:15,366 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:58:27,970 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 11:58:56,269 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 12:00:12,347 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 12:00:44,060 ERROR: Exception on /CIR [POST] [in c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Reports\Applications\web_CIR\app\routes.py", line 59, in CIR
    CIR_mail(current_user, report)
  File "C:\Reports\Applications\web_CIR\app\email.py", line 13, in CIR_mail
    sender = config['ADMINS'][0]
TypeError: 'module' object is not subscriptable
2020-01-13 12:02:14,132 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 12:02:20,691 ERROR: Exception on /CIR [POST] [in c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Reports\Applications\web_CIR\app\routes.py", line 59, in CIR
    CIR_mail(current_user, report)
  File "C:\Reports\Applications\web_CIR\app\email.py", line 14, in CIR_mail
    recipients = SchoolLookup.query.filter_by(school_name=f'{report.school_name}').first()
NameError: name 'SchoolLookup' is not defined
2020-01-13 12:03:18,833 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 12:03:22,825 ERROR: Exception on /CIR [POST] [in c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Reports\Applications\web_CIR\app\routes.py", line 59, in CIR
    CIR_mail(current_user, report)
  File "C:\Reports\Applications\web_CIR\app\email.py", line 45, in CIR_mail
    msg = Message(mail_subj, sender=sender, recipients=recipients, text_body=body)
TypeError: __init__() got an unexpected keyword argument 'text_body'
2020-01-13 12:05:22,156 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 12:05:28,253 ERROR: Exception on /CIR [POST] [in c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Reports\Applications\web_CIR\app\routes.py", line 59, in CIR
    CIR_mail(current_user, report)
  File "C:\Reports\Applications\web_CIR\app\email.py", line 46, in CIR_mail
    mail.send(msg)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 175, in send
    assert message.send_to, "No recipients have been added"
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 296, in send_to
    return set(self.recipients) | set(self.bcc or ()) | set(self.cc or ())
TypeError: 'SchoolLookup' object is not iterable
2020-01-13 12:09:02,657 INFO: Web CIR startup [in C:\Reports\Applications\web_CIR\app\__init__.py:47]
2020-01-13 12:09:08,440 ERROR: Exception on /CIR [POST] [in c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Reports\Applications\web_CIR\app\routes.py", line 59, in CIR
    CIR_mail(current_user, report)
  File "C:\Reports\Applications\web_CIR\app\email.py", line 47, in CIR_mail
    mail.send(msg)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 181, in send
    if message.has_bad_headers():
  File "c:\reports\applications\web_cir\venv\lib\site-packages\flask_mail.py", line 400, in has_bad_headers
    headers = [self.sender, self.reply_to] + self.recipients
TypeError: can only concatenate list (not "str") to list
